---

- name: Setup the list of bridges
  set_fact:
    networking_bridgenames: []

- name: Generate list of bridges
  set_fact:
    networking_cloned_interfaces: "{{ networking_bridgenames + [ item.name ] }}"
  with_items: "{{ networking_bridges }}"

- name: Demonstrate list of cloned interfaces
  debug: var=networking_bridgenames

