---

- name: Setup empty list of cloned interfaces
  set_fact:
    networking_cloned_interfaces: []

# NOTE: Principle of least surprise
#
# Epairs get created starting from zero, which means we get one interface
# too many if we document 'networking_epairs' to mean 'number of epairs requested',
# so we substract one from the sequence.

- name: Add epairs to cloned interfaces
  set_fact:
    networking_cloned_interfaces: "{{ networking_cloned_interfaces }} + [ '{{ item }}' ]"
  with_sequence: start=0 end="{{ networking_epairs | int - 1 }}" format=epair%d
  when: networking_epairs is defined and networking_epairs | int > 0

- name: Add bridges to cloned interfaces
  set_fact:
    networking_cloned_interfaces: "{{ networking_cloned_interfaces }} + [ '{{ item.iface }}' ]"
  with_items: "{{ networking_interfaces | selectattr('members','defined') | list }}"

- name: Add epairs to list of cloned interfaces
  set_fact:
    networking_cloned_interfaces: "{{ networking_cloned_interfaces }} + {{ networking_epairs_list }}"
  when: networking_epairs_list is defined and networking_epairs_list | length > 0

- name: Unroll the list of cloned interfaces into the configuration file
  sysrc:
    dest: "/etc/rc.conf"
    name: cloned_interfaces
    value: "{{ networking_cloned_interfaces | join(' ') }}"
  when: networking_cloned_interfaces is defined and (networking_cloned_interfaces | length > 0)
