---

- name: Merge sources of cloned interfaces
  set_fact:
    networking_cloned_interfaces: "{{ networking_bridgenames }}"
  when: networking_bridgenames is defined and (networking_bridgenames | length > 0)

- name: Cloned interfaces equals the list of bridges for now
  lineinfile:
    path: "/etc/rc.conf"
    regexp: "^cloned_interfaces="
    line: cloned_interfaces="{{ networking_cloned_interfaces | join(' ') }}"
  when: networking_cloned_interfaces is defined and (networking_cloned_interfaces | length > 0)
