---

# Configure IPv4 networking
- import_tasks: interface_ipv4.yml

# Configure bridging on the interface if requested
- import_tasks: interface_bridge.yml
  when: item.members is defined

# Configure IPv6 networking
- include_tasks: interface_ipv6.yml
  when: item.ipv6_address is defined or item.ipv6_slaac is sameas true

# Configure VLAN's on the interface
- import_tasks: interface_vlan.yml
  when: item.vlans is defined

# Combine the settings into an ifconfig-variable in rc.conf
- name: Roll the ifconfig list into a single line for {{ item.iface }}
  sysrc:
    dest: /etc/rc.conf
    name: "ifconfig_{{ item.iface | replace('.','_') }}"
    value: "{{ networking_iface_ifconfig | join(' ') }}"
  when: networking_iface_ifconfig is defined and networking_iface_ifconfig | length > 0
  notify: Restart networking
