---

- name: Configure {{ item.name }}
  lineinfile:
    path: /etc/rc.conf
    regexp: "^ifconfig_{{ item.name }}="
    line: ifconfig_{{ item.name }}="inet {{ item.ipv4_address }} netmask {{ item.ipv4_netmask }}"
