---

- name: Configure static IPv4 on {{ item.iface }}
  lineinfile:
    path: /etc/rc.conf
    regexp: "^ifconfig_{{ item.iface }}="
    line: ifconfig_{{ item.iface }}="inet {{ item.ipv4_address }} netmask {{ item.ipv4_netmask }}"
  notify: Restart networking

