---

- name: Initialize list of ifconfig fragments
  set_fact:
    networking_iface_ifconfig: []

- name: Assume we're not dealing with a bridge
  set_fact:
    networking_iface_is_bridge: false

- name: Check if {{ item.iface }} actually is a bridge
  set_fact:
    networking_iface_is_bridge: true
  when: item.members is defined

- name: Initialize empty list for brigde-member fragments
  set_fact:
    networking_iface_members: []
  when: networking_iface_is_bridge

- name: Generate fragment for static IPv4 configuration on {{ item.iface }}
  set_fact:
    networking_iface_ifconfig: "{{ networking_iface_ifconfig }} + [ 'inet {{ item.ipv4_address | ipv4 }} netmask {{ item.ipv4_netmask | ipv4 }}' ]"
  when: (item.ipv4_dhcp is not defined or item.ipv4_dhcp is sameas false) and 'ipv4_address' in item

- name: Generate fragment for IPv4 configuration through DHCP on {{ item.iface }}
  set_fact:
    networking_iface_ifconfig: "{{ networking_iface_ifconfig }} + [ '{{ networking_dhcp_type | upper }}' ]"
  when: item.ipv4_dhcp is defined and item.ipv4_dhcp

- name: Generate ifconfig fragment for {{ item.iface }}  members if we are dealing with a bridge
  set_fact:
    networking_iface_members: "{{ networking_iface_members }} + [ 'addm {{ member }}' ]"
  with_items: "{{ item.members }}"
  loop_control:
    loop_var: member
  when: networking_iface_is_bridge

- name: Combine all bridge members for {{ item.iface }} into a single ifconfig fragment
  set_fact:
    networking_iface_membersfragment: "{{ networking_iface_members | join(' ') }}"
  when: networking_iface_is_bridge

- name: Put the bridge members ifconfig fragment on the stack for {{ item.iface }}
  set_fact:
    networking_iface_ifconfig: "{{ networking_iface_ifconfig }} + [ '{{ networking_iface_membersfragment }}' ]"
  when: networking_iface_is_bridge

- name: Configure VLAN's on {{ item.iface }}
  sysrc:
    name: "vlans_{{ item.iface }}"
    value: "{{ item.vlans | join(' ') }}"
  notify: Restart networking
  when: item.vlans is defined

- name: set network interface state
  set_fact:
    networking_iface_ifconfig: "{{ networking_iface_ifconfig }} + [ '{{ item.state }}' ]"
  when: item.state is defined


- name: Roll the ifconfig list into a single line for {{ item.iface }}
  sysrc:
    dest: /etc/rc.conf
    name: "ifconfig_{{ item.iface | replace('.','_') }}"
    value: "{{ networking_iface_ifconfig | join(' ') }}"
  when: networking_iface_ifconfig is defined and networking_iface_ifconfig | length > 0
  notify: Restart networking

- include_tasks: interface_ipv6.yml
  when: item.ipv6_address is defined or ipv6_slaac
