---

- name: Configure IPv4 default gateway
  lineinfile:
    path: /etc/rc.conf
    regexp: "^defaultrouter="
    line: defaultrouter="{{ networking_ipv4_gateway }}"
  when: networking_gateway_dhcp == false
  notify: Restart networking

- name: Remove statically configured IPv4 gateway
  lineinfile:
    path: /etc/rc.conf
    regexp: "^defaultrouter="
    state: absent
  when: networking_gateway_dhcp == true or networking_ipv4_gateway is undefined

