---

- name: Configure IPv6 default gateway
  sysrc:
    dest: /etc/rc.conf
    name: ipv6_defaultrouter
    value: "{{ networking_ipv6_gateway }}"
  when: networking_ipv6_gateway is defined
  notify: Restart networking

- name: Remove statically configured IPv6 gateway
  sysrc:
    dest: /etc/rc.conf
    name: ipv6_defaultrouter
    state: absent
  when: networking_ipv6_gateway is undefined
  notify: Restart networking
