---

- include_tasks: hostname.yml
  when: networking_hostname is defined
- include_tasks: interface.yml
  loop: "{{ networking_interfaces }}"
  when: networking_interfaces is defined
- include_tasks: ipv4_gateway.yml
- include_tasks: ipv6_gateway.yml
- include_tasks: resolvers.yml
  when: networking_resolvers_dhcp is sameas false
