---

- name: Restart networking
  command:
    cmd: "/etc/rc.d/netif restart && sleep 5 && /etc/rc.d/routing restart"
  when: networking_autorestart

- name: Force restart networking
  command:
    cmd: "/etc/rc.d/netif restart && sleep 5 && /etc/rc.d/routing restart"

- name: Enable rtsold
  service:
    name: rtsold
    state: started
    enabled: true

- name: Disable rtsold
  service:
    name: rtsold
    state: stopped
    enabled: false

